
####2020/08/20 22:22:14####
Traceback (most recent call last):
  File "main.py", line 1731, in th_saver
    business_contact(status)
  File "main.py", line 1181, in business_contact
    content = util.content_cleanser(status['content'])
  File "/Users/ssug/python/kiri_bot/util.py", line 64, in content_cleanser
    tmp = BeautifulSoup(content.replace("<br />","___R___").strip(),'lxml')
  File "/Users/ssug/python/kiri_bot/venv_dev/lib/python3.7/site-packages/bs4/__init__.py", line 245, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

####2020/08/20 22:25:42####
Traceback (most recent call last):
  File "main.py", line 1731, in th_saver
    business_contact(status)
  File "main.py", line 1181, in business_contact
    content = util.content_cleanser(status['content'])
  File "/Users/ssug/python/kiri_bot/util.py", line 87, in content_cleanser
    ng_words = set(word.strip() for word in open('.ng_words').readlines())
FileNotFoundError: [Errno 2] No such file or directory: '.ng_words'

####2020/08/20 22:28:41####
Traceback (most recent call last):
  File "main.py", line 1731, in th_saver
    business_contact(status)
  File "main.py", line 1181, in business_contact
    content = util.content_cleanser(status['content'])
  File "/Users/ssug/python/kiri_bot/util.py", line 87, in content_cleanser
    ng_words = set(word.strip() for word in open(NG_WORDS_PATH).readlines())
FileNotFoundError: [Errno 2] No such file or directory: '.ng_words'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1731, in th_saver
    business_contact(status)
  File "main.py", line 1181, in business_contact
    content = util.content_cleanser(status['content'])
  File "/Users/ssug/python/kiri_bot/util.py", line 87, in content_cleanser
    ng_words = set(word.strip() for word in open(NG_WORDS_PATH).readlines())
FileNotFoundError: [Errno 2] No such file or directory: '.ng_words'

####2020/08/20 22:59:50####
Traceback (most recent call last):
  File "main.py", line 1731, in th_saver
    business_contact(status)
  File "main.py", line 1181, in business_contact
    content = util.content_cleanser(status['content'])
  File "/Users/ssug/python/kiri_bot/util.py", line 87, in content_cleanser
    ng_words = set(word.strip() for word in open(NG_WORDS_PATH).readlines())
FileNotFoundError: [Errno 2] No such file or directory: '.ng_words'

####2020/08/20 23:00:10####
Traceback (most recent call last):
  File "main.py", line 1731, in th_saver
    business_contact(status)
  File "main.py", line 1181, in business_contact
    content = util.content_cleanser(status['content'])
  File "/Users/ssug/python/kiri_bot/util.py", line 87, in content_cleanser
    ng_words = set(word.strip() for word in open(NG_WORDS_PATH).readlines())
FileNotFoundError: [Errno 2] No such file or directory: '.ng_words'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1731, in th_saver
    business_contact(status)
  File "main.py", line 1181, in business_contact
    content = util.content_cleanser(status['content'])
  File "/Users/ssug/python/kiri_bot/util.py", line 87, in content_cleanser
    ng_words = set(word.strip() for word in open(NG_WORDS_PATH).readlines())
FileNotFoundError: [Errno 2] No such file or directory: '.ng_words'

####2020/08/20 23:05:02####
Traceback (most recent call last):
  File "/Users/ssug/python/kiri_bot/util.py", line 124, in scheduler
    func()
  File "main.py", line 1447, in bottlemail_sending
    bm = bottlemail.Bottlemail()
  File "/Users/ssug/python/kiri_bot/bottlemail.py", line 19, in __init__
    con = sqlite3.connect(self.DB_PATH)
sqlite3.OperationalError: unable to open database file

####2020/08/20 23:05:12####
Traceback (most recent call last):
  File "/Users/ssug/python/kiri_bot/util.py", line 124, in scheduler
    func()
  File "main.py", line 1447, in bottlemail_sending
    bm = bottlemail.Bottlemail()
  File "/Users/ssug/python/kiri_bot/bottlemail.py", line 19, in __init__
    con = sqlite3.connect(self.DB_PATH)
sqlite3.OperationalError: unable to open database file

####2020/08/20 23:05:22####
Traceback (most recent call last):
  File "/Users/ssug/python/kiri_bot/util.py", line 124, in scheduler
    func()
  File "main.py", line 1447, in bottlemail_sending
    bm = bottlemail.Bottlemail()
  File "/Users/ssug/python/kiri_bot/bottlemail.py", line 19, in __init__
    con = sqlite3.connect(self.DB_PATH)
sqlite3.OperationalError: unable to open database file

####2020/08/20 23:05:32####
Traceback (most recent call last):
  File "/Users/ssug/python/kiri_bot/util.py", line 124, in scheduler
    func()
  File "main.py", line 1447, in bottlemail_sending
    bm = bottlemail.Bottlemail()
  File "/Users/ssug/python/kiri_bot/bottlemail.py", line 19, in __init__
    con = sqlite3.connect(self.DB_PATH)
sqlite3.OperationalError: unable to open database file
